### ISSUE TITLE
Pec

### ISSUE THREAD

**Issue by pigorg** [Hevelop/invoice-request#13]
Missing the email PEC.

**Comment by SamueleMartini** [comment]
> Missing the email PEC.

The PEC is not required ed if there is the SDI code.

**Comment by mickymix** [comment]
I would suggest a PEC to be present in any case.
There are customers which would need an invoice with a personal Tax Code (Codice Fiscale), while not having an SDI Code.
PEC would permit PUSH, instead of PULL notification.
JMTC

**Comment by SamueleMartini** [comment]
> I would suggest a PEC to be present in any case. There are customers which would need an invoice with a personal Tax Code (Codice Fiscale), while not having an SDI Code. PEC would permit PUSH, instead of PULL notification. JMTC

@mickymix all customers have a SDI code. Fiscal people, sports associations, voluntary associations or freelance with flat-rate basis (regime forfettario) have "0000000" as SDI code.
When you request an invoice as a private individual, simply enter the data requested by the form. The merchant knows that being a private individual, he must issue the invoice by default to the sdi code 0000000

**Comment by mickymix** [comment]
@SamueleMartini I just meant that, while having a "0000000" SDI Code, those customers might have a PEC where they could prefer receiving a PUSHED invoice, instead of PULLING it from "Cassetto Fiscale".
