### ISSUE TITLE
Mageplaza One Step Checkout compatibility

### ISSUE THREAD

**Issue by ilevennet** [Hevelop/invoice-request#14]
The module does not appear to be compatible with the Mageplaza OSC.

Il modulo non risulta essere compatibile con l'estensione in oggetto.
Sarebbe utile aggiungere questa possibilità.

**Comment by SamueleMartini** [comment]
Il modulo è un modulo per Magento, non per Mageplaza. Non possiamo cucire il modulo su misura per tutti i checkout di terze parti, né favorire Mageplaza rispetto ad altri vendor.
Il modulo ha comunque il codice in chiaro perciò puoi facilmente forcarlo oppure aggiungere funzionalità al tuo progetto.

**Comment by ilevennet** [comment]
Ciao Samuele Grazie per la risposta. Era solo un suggerimento per avere compatibilità con uno dei più venduti OSC. Ci proveremo, grazie ancora e complimenti per l'ottimo lavoro!
