### ISSUE TITLE
Recupero SDI nella Richiesta Fattura nella pagina di Checkout

### ISSUE THREAD

**Issue by ITA003** [Hevelop/invoice-request#15]
Ciao Ho riscontrato un problema nella pagina di Checkout e la selezione del campo SDI.

Il Campo è stato correttamente compilato dalla Gestione Indirizzi dell'utente, ma nella pagina di checkout i campi Ragione Sociale, Codice Fiscale e P.IVA sono correttamente compilati mentre il campo SDI no (Vedi screenshot)

![Screenshot_20210423_104409](https://user-images.githubusercontent.com/7451972/115845288-fa4a1580-a420-11eb-97cc-d7d21e12e4c6.png)

Ho notato che nella tabella customer_address_entity il campo sdi_code non è compilato mentre lo è nella tabella degli attributi customer_address_entity_varchar

Non dovrebbe essere compilato anche nella tabella customer_address_entity?

Versione di Magento 2.4.1 e Php 7.4.16

**Comment by SamueleMartini** [comment]
> Ciao Ho riscontrato un problema nella pagina di Checkout e la selezione del campo SDI.
> 
> Il Campo è stato correttamente compilato dalla Gestione Indirizzi dell'utente, ma nella pagina di checkout i campi Ragione Sociale, Codice Fiscale e P.IVA sono correttamente compilati mentre il campo SDI no (Vedi screenshot)
> 
> ![Screenshot_20210423_104409](https://user-images.githubusercontent.com/7451972/115845288-fa4a1580-a420-11eb-97cc-d7d21e12e4c6.png)
> 
> Ho notato che nella tabella customer_address_entity il campo sdi_code non è compilato mentre lo è nella tabella degli attributi customer_address_entity_varchar
> 
> Non dovrebbe essere compilato anche nella tabella customer_address_entity?
> 
> Versione di Magento 2.4.1 e Php 7.4.16

Salve,
nella tabella customer_address_entity è corretto che non sia valorizzato, in quanto gli address sono entità gestite con l'EAV, nella tabella principale dell'entity ci vanno solo gli attributi contrassegnati come "static".

Per il problema della compilazione a checkout, non riesco a riprodurre la casistica. Sta utilizzando un tema custom/acquistato o ha il problema anche su Luma?

Grazie.

**Comment by ITA003** [comment]
Il problema è presente anche con il tema Luma.

Questa è la schermata della Rubrica Indirizzi:

![Screenshot_2021-04-28_1152](https://user-images.githubusercontent.com/7451972/116384514-34982600-a818-11eb-9a72-76c2d046a5f4.png)

Mentre questa è la pagina di Checkout:

![Screenshot_2021-04-28_1151](https://user-images.githubusercontent.com/7451972/116384426-1f22fc00-a818-11eb-8842-d76075783e77.png)
