### ISSUE TITLE
Aggiornamento via API

### ISSUE THREAD

**Issue by enricodeleo** [Hevelop/invoice-request#16]
Ciao e grazie per questa utilissima estensione! Tentando un update dell'indirizzo attraverso api ottengo questo errore:

```
[2021-06-30 06:50:38] main.CRITICAL: Report ID: webapi-60dc143e97eda; Message: Property "SdiCode" does not have accessor method "getSdiCode" in class "Magento\Customer\Api\Data\AddressInterface". {"exception":"[object] (Exception(code: 0): Report ID: webapi-60dc143e97eda; Message: Property \"SdiCode\" does not have accessor method \"getSdiCode\" in class \"Magento\\Customer\\Api\\Data\\AddressInterface\". at /app/vendor/magento/framework/Webapi/ErrorProcessor.php:208, LogicException(code: 0): Property \"SdiCode\" does not have accessor method \"getSdiCode\" in class \"Magento\\Customer\\Api\\Data\\AddressInterface\". at /app/vendor/magento/framework/Reflection/NameFinder.php:103)"} []
```

È un problema noto? Sbaglio qualcosa?

**Comment by SamueleMartini** [comment]
> Ciao e grazie per questa utilissima estensione! Tentando un update dell'indirizzo attraverso api ottengo questo errore:
> 
> ```
> [2021-06-30 06:50:38] main.CRITICAL: Report ID: webapi-60dc143e97eda; Message: Property "SdiCode" does not have accessor method "getSdiCode" in class "Magento\Customer\Api\Data\AddressInterface". {"exception":"[object] (Exception(code: 0): Report ID: webapi-60dc143e97eda; Message: Property \"SdiCode\" does not have accessor method \"getSdiCode\" in class \"Magento\\Customer\\Api\\Data\\AddressInterface\". at /app/vendor/magento/framework/Webapi/ErrorProcessor.php:208, LogicException(code: 0): Property \"SdiCode\" does not have accessor method \"getSdiCode\" in class \"Magento\\Customer\\Api\\Data\\AddressInterface\". at /app/vendor/magento/framework/Reflection/NameFinder.php:103)"} []
> ```
> 
> È un problema noto? Sbaglio qualcosa?

Ciao,
ti dà questo errore solo se cerchi di settare un nuovo SDI Code, o anche aggiornando un qualsiasi altro parametro e lasciando lo SDI inalterato?

**Comment by enricodeleo** [comment]
Ciao @SamueleMartini e grazie della risposta. Questo avviene sempre via api. In realtà credo di aver trovato la soluzione evidentemente ero io a non aver seguito la prassi di Magento. Banalmente ho passato il valore come oggetto nell'array degli extension attributes ed in questo modo non ho riscontrato ostacoli.

**Comment by SamueleMartini** [comment]
> Ciao @SamueleMartini e grazie della risposta. Questo avviene sempre via api. In realtà credo di aver trovato la soluzione evidentemente ero io a non aver seguito la prassi di Magento. Banalmente ho passato il valore come oggetto nell'array degli extension attributes ed in questo modo non ho riscontrato ostacoli.

Eh infatti, ti avevo chiesto appositamente per capire se lo passavi come extension attribute o meno.
Sentiti libero di fare una pull request aggiornano il Readme del modulo per quanto riguarda le API, se a tuo avviso questo punto andrebbe chiarito.
