### ISSUE TITLE
Richiesta informazioni 

### ISSUE THREAD

**Issue by Alessandrog72** [Hevelop/invoice-request#4]
Buonasera Davide   premetto che non sono un esperto di Magento , mi stò avvicinando a questo software prodotto piano piano. Sono interessato ad installare il tuo sciprt , mi potresti dare qualche consiglio per installarto  ? Ho trovato questo sito  https://firebearstudio.com/blog/come-installare-moduli-di-magento-estensioni.html  va bene per installare il tuo modulo ? 

Grazie Alessandro

**Comment by SamueleMartini** [comment]
> Buonasera Davide premetto che non sono un esperto di Magento , mi stò avvicinando a questo software prodotto piano piano. Sono interessato ad installare il tuo sciprt , mi potresti dare qualche consiglio per installarto ? Ho trovato questo sito https://firebearstudio.com/blog/come-installare-moduli-di-magento-estensioni.html va bene per installare il tuo modulo ?
> 
> Grazie Alessandro

Salve Alessandro,
il modulo si installa tramite composer, come suggerito anche dalla guida che hai citato.
Il comando è "composer require hevelop/invoice-request"
In alternativa puoi scaricare il modulo tramite l'apposito pulsante qui su github, e copiare il contenuto nelle cartelle "app/code/Hevelop/InvoiceRequest"

_Samuele_
