### ISSUE TITLE
Fields for private invoice shown instead of company ones when billing address it's updated after "i want invoice" selection

### ISSUE THREAD

**Issue by alenalato** [Hevelop/invoice-request#6]
Effect: Cannot place order but no errors on page

Steps to reproduce (on checkout payment step, as a guest):
1. uncheck "My billing and shipping address are the same"
1. compile billing address form, don't save form (i.e. don't click update nor cancel)
1. select "i want invoice"
1. select "business": fields are missing
1. save billing address form: fields won't appear
or
1. check again "My billing and shipping address are the same": fields still not shown

Exptected beahavior
1. uncheck "My billing and shipping address are the same"
1. compile billing address form, don't save form (i.e. don't click update nor cancel)
1. select "i want invoice"
1. select "business": fields are missing
1. save billing address form: fields appear
or
1. check again "My billing and shipping address are the same": fields appear

**Comment by SamueleMartini** [comment]
Issue solved by Dadolun with pull request https://github.com/Hevelop/invoice-request/pull/10
