### ISSUE TITLE
Compatibilità?

### ISSUE THREAD

**Issue by antonioste** [Hevelop/invoice-request#7]
Salve,
non riesco a trovare la compatibilità con Magento 2.2 e 2.3, è compatibile? Posso provarlo in ambiente test?

grazie

**Comment by WaPoNe** [comment]
@antonioste the 2.2 version is no longer supported by Magento.
You have to upgrade your Magento 2.2 instances.

**Comment by manuel-inhertz** [comment]
@antonioste Dovrebbe essere compatibile, puoi testarlo.
